# Generated by Django 4.0.5 on 2022-06-18 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_clickcourse_date_alter_course_addtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickcourse',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 12, 58, 9, 601477)),
        ),
        migrations.AlterField(
            model_name='course',
            name='addTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 12, 58, 9, 591213)),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(default='<function uuid4 at 0x7f9ddb4e1a20>', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 12, 58, 9, 597114)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 12, 58, 9, 600596)),
        ),
        migrations.AlterField(
            model_name='publish',
            name='id',
            field=models.UUIDField(default='<function uuid4 at 0x7f9ddb4e1a20>', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 12, 58, 9, 602392)),
        ),
        migrations.AlterField(
            model_name='teachermakecourse',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 12, 58, 9, 596644)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 12, 58, 9, 591757)),
        ),
        migrations.AlterField(
            model_name='usersearchcourse',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 12, 58, 9, 598938)),
        ),
        migrations.AlterField(
            model_name='watchcourse',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 12, 58, 9, 601945)),
        ),
    ]
