# Generated by Django 3.2.13 on 2022-05-31 04:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20220531_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishersocalmedia',
            name='publisher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.publisher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersocalmedia',
            name='user',
            field=models.ForeignKey(default='982c797f-e045-4ce0-ae5b-61d383f9eef4', on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clickcourse',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 8, 44, 41, 484143)),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 8, 44, 41, 479985)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 8, 44, 41, 483371)),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 8, 44, 41, 485126)),
        ),
        migrations.AlterField(
            model_name='teachermakecourse',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 8, 44, 41, 479537)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 8, 44, 41, 474552)),
        ),
        migrations.AlterField(
            model_name='usersearchcourse',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 8, 44, 41, 481773)),
        ),
        migrations.AlterField(
            model_name='watchcourse',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 8, 44, 41, 484711)),
        ),
    ]
