# Generated by Django 4.0.5 on 2022-07-03 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_payment_time_alter_course_addtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='isUP',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='addTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 19, 50, 6, 444546)),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 19, 50, 6, 451600)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 19, 50, 6, 455059)),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 19, 50, 6, 456536)),
        ),
        migrations.AlterField(
            model_name='teachermakecourse',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 19, 50, 6, 451121)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 19, 50, 6, 445363)),
        ),
        migrations.AlterField(
            model_name='usersearchcourse',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 19, 50, 6, 453399)),
        ),
        migrations.AlterField(
            model_name='watchcourse',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 19, 50, 6, 456122)),
        ),
    ]
