# Generated by Django 4.0.5 on 2022-07-03 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_contactus_time_alter_contactus_subject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='time',
            field=models.DateField(default=datetime.datetime(2022, 7, 3, 23, 3, 40, 400348)),
        ),
        migrations.AlterField(
            model_name='course',
            name='addTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 23, 3, 40, 388082)),
        ),
        migrations.AlterField(
            model_name='coursecomment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 23, 3, 40, 395101)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 23, 3, 40, 398607)),
        ),
        migrations.AlterField(
            model_name='searchlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 23, 3, 40, 400001)),
        ),
        migrations.AlterField(
            model_name='teachermakecourse',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 23, 3, 40, 394664)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 23, 3, 40, 388926)),
        ),
        migrations.AlterField(
            model_name='usersearchcourse',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 23, 3, 40, 396900)),
        ),
        migrations.AlterField(
            model_name='watchcourse',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 23, 3, 40, 399581)),
        ),
    ]
